import {
  AgentsInstructionsSlide,
  AskQuestionsSlide,
  BringApproachSlide,
  BuildForAgentsSlide,
  ClosingSlide,
  CoreFrameworkSlide,
  DELEGATE_SUBAGENTS_STEP_COUNT,
  DelegateSubagentsSlide,
  HowAgentsWorkSlide,
  ManageContextSlide,
  ModelSelectionSlide,
  ParallelWorkflowsSlide,
  PlanFirstSlide,
  PlayToStrengthsSlide,
  SkillsTechniqueSlide,
  TitleSlide,
  TOOLING_FEATURES_STEP_COUNT,
  TOKEN_PROBLEM_STEP_COUNT,
  TokenProblemSlide,
  ToolingFeaturesSlide,
  TurnOffUnusedMcpsSlide,
} from './content';
import { speakerNotes } from './speakerNotes';
import type { Deck } from '../types';
import { ConstellationBackground } from './ConstellationBackground';

export const deck: Deck = {
  id: 'agentic-coding',
  title: 'Agentic Coding: Harness & Optimisation',
  blurb: 'How agents work, the harness, and techniques for getting the most out of them.',
  themeClass: 'theme-terminal',
  Background: ConstellationBackground,
  enableLaser: true,
  footerHint: '← → / Space / Home / End',
  interactiveStepCounts: {
    2: TOKEN_PROBLEM_STEP_COUNT,
    3: TOOLING_FEATURES_STEP_COUNT,
    9: DELEGATE_SUBAGENTS_STEP_COUNT,
  },
  speakerNotes,
  slides: [
    TitleSlide,
    HowAgentsWorkSlide,
    TokenProblemSlide,
    ToolingFeaturesSlide,
    CoreFrameworkSlide,
    PlanFirstSlide,
    AskQuestionsSlide,
    BringApproachSlide,
    PlayToStrengthsSlide,
    DelegateSubagentsSlide,
    AgentsInstructionsSlide,
    SkillsTechniqueSlide,
    ManageContextSlide,
    ModelSelectionSlide,
    TurnOffUnusedMcpsSlide,
    BuildForAgentsSlide,
    ParallelWorkflowsSlide,
    ClosingSlide,
  ],
};
